### ISSUE TITLE
Most results are reproducible!!

### ISSUE THREAD

**Issue by tarun005** [virajprabhu/SENTRY#2]
I could reproduce most results given in the paper on Office Home and domainNet datasets. Well done on this great work and thanks for making the code available to public!

As a side note, I noticed that not all the methods you compare against use the same evaluation process, like center crop on Cliparts. It would be great if you could prepare a comparison across all baselines using the same evaluation methods.

**Comment by virajprabhu** [comment]
Thanks, glad you could reproduce our results. That's a good point, we actually include that comparison in Tables 9-10 of our appendix: https://arxiv.org/pdf/2012.11460.pdf. Or did you mean something else?
