### ISSUE TITLE
how can I reproduce svhn->mnist for LDS_type=IF50

### ISSUE THREAD

**Issue by CYDping** [virajprabhu/SENTRY#4]
Hi, thanks for sharing. 

But I found in Digit Dataset, we only can reproduce LDS_type=IF20 as in Checkpoints folder there only has mnist_ixs_IF20.pkl. 

So what we can do if we want to reproduce other result, like LDS_type=IF50/100. How can we make .pkl files like yours? Could you help us with this problem? 

Thanks a lot.

**Comment by virajprabhu** [comment]
I've pushed those pickle files to the same directory. Lmk if you still have trouble reproducing results!
