### ISSUE TITLE
what it means when committee size k is larger than the augmented number N in Table 6 of the paper?

### ISSUE THREAD

**Issue by fake-warrior8** [virajprabhu/SENTRY#5]
Hi, I'd like to know what it means when committee size k is larger than the augmented number N in Table 6 of the paper? I think the committee size k should be smaller than the augmented number.
![S6G_TRZ2Z}K)I}7`JP2$7CH](https://user-images.githubusercontent.com/40395156/160608667-1a3b94f1-9576-4107-a7d6-5fd40cd8abaf.png)

**Comment by virajprabhu** [comment]
N corresponds to the number of consecutive transforms applied by RandAugment to generate each committee member. So k and N are independent and can take on arbitrary values.
